//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "statistics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub version: String,
    pub command: String,
    pub executed_at: DateTimeWithTimeZone,
    pub success: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_msg: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
