[package]
name = "tobi-rs"
version = "0.9.3"
authors = ["trivernis <trivernis@protonmail.com>"]
edition = "2018"

[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bot-database = {path="./bot-database"}
bot-coreutils = {path="./bot-coreutils"}
serenity-rich-interaction = "0.2.2"
serenity = "0.10.5"
dotenv = "0.15.0"
tokio = { version = "1.4.0", features = ["macros", "rt-multi-thread"] }
serde_derive = "1.0.125"
serde = "1.0.125"
thiserror = "1.0.24"
minecraft-data-rs = "0.3.0"
songbird =  "0.1.5"
serde_json = "1.0.64"
rand = "0.8.3"
regex = "1.4.5"
aspotify = "0.7.0"
lazy_static = "1.4.0"
futures = "0.3.13"
log = "0.4.14"
fern = "0.6.0"
chrono = "0.4.19"
colored = "2.0.0"
sysinfo = "0.16.5"
reqwest = "0.11.2"
chrono-tz = "0.5.3"
sauce-api = "0.7.1"
rustc_version_runtime = "0.2.0"
trigram = "0.4.4"
typemap_rev = "0.1.5"
youtube-metadata = "0.1.1"
xkcd-search = "0.1.1"
lavalink-rs = {version="0.7.1", features=["native", "serenity"]}
animethemes-rs = "0.2.1"